Repository peercoin/peercoin_flutter, pull requests merged in 2022-02, with the labels that each got.

#126 0.8.1
  CHANGELOG.md
  README.md
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/es.json
  assets/translations/fr.json
  assets/translations/hr.json
  assets/translations/it.json
  assets/translations/nl.json
  assets/translations/pl.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/zh.json
  lib/providers/activewallets.dart
  lib/providers/electrumconnection.dart
  lib/screens/app_settings_screen.dart
  lib/screens/server_add.dart
  lib/screens/setup/setup_import_seed.dart
  lib/screens/wallet/import_paper_wallet.dart
  lib/tools/app_localizations.dart
  lib/widgets/wallet/send_tab.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, chore

#128 0.8.2
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/coinerella/peercoin_flutter/MainActivity.kt
  android/app/src/main/kotlin/com/example/peercoin/MainActivity.kt
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/frm.json
  assets/translations/hr.json
  assets/translations/it.json
  assets/translations/nb_NO.json
  assets/translations/nl.json
  assets/translations/pt.json
  assets/translations/tr.json
  fastlane/metadata/android/en-US/full_description.txt
  ios/Podfile.lock
  lib/screens/setup/setup_create_wallet.dart
  lib/screens/setup/setup_import_seed.dart
  lib/tools/app_localizations.dart
  lib/tools/app_themes.dart
  lib/tools/notification.dart
  lib/tools/price_ticker.dart
  lib/widgets/buttons.dart
  lib/widgets/setup_progress.dart
  lib/widgets/wallet/receive_tab.dart
  lib/widgets/wallet/transactions_list.dart
  pubspec.lock
  pubspec.yaml
  test_driver/key_imported.dart
  test_driver/key_new.dart
Labels: enhancement, chore

#130 0.8.3
  CHANGELOG.md
  android/app/build.gradle
  assets/translations/en.json
  lib/tools/app_localizations.dart
  lib/tools/price_ticker.dart
  pubspec.yaml
Labels: bug, chore

#138 0.8.4
  CHANGELOG.md
  assets/translations/bn_BD.json
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/es.json
  assets/translations/fa.json
  assets/translations/fil.json
  assets/translations/fr.json
  assets/translations/frm.json
  assets/translations/ha.json
  assets/translations/hi.json
  assets/translations/id.json
  assets/translations/it.json
  assets/translations/ja.json
  assets/translations/ko.json
  assets/translations/nb_NO.json
  assets/translations/nl.json
  assets/translations/pl.json
  assets/translations/pt.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/sw.json
  assets/translations/th.json
  assets/translations/tr.json
  assets/translations/uk.json
  assets/translations/ur.json
  assets/translations/vi.json
  assets/translations/zh.json
  lib/providers/activewallets.dart
  lib/screens/setup/setup.dart
  lib/screens/wallet/wallet_list.dart
  lib/tools/app_localizations.dart
  lib/tools/backgroundsync.dart
  lib/tools/price_ticker.dart
  lib/widgets/buttons.dart
  lib/widgets/wallet/addresses_tab.dart
  lib/widgets/wallet/send_tab.dart
  pubspec.lock
  pubspec.yaml
  test_driver/key_imported.dart
  test_driver/key_new.dart
Labels: bug, enhancement, chore

#141 0.8.5
  CHANGELOG.md
  assets/translations/ar.json
  assets/translations/el.json
  assets/translations/en.json
  assets/translations/fil.json
  assets/translations/ja.json
  assets/translations/nb_NO.json
  assets/translations/th.json
  lib/screens/setup/setup_create_wallet.dart
  lib/screens/setup/setup_data_feeds.dart
  lib/screens/setup/setup_import_seed.dart
  lib/screens/wallet/import_paper_wallet.dart
  lib/tools/app_localizations.dart
  lib/tools/price_ticker.dart
  lib/widgets/buttons.dart
  pubspec.yaml
Labels: bug, enhancement, chore
